package com.spotahome.enums;

public enum City {
    BARCELONA, BERLIN, BILBAO, BOLOGNA, BRUSSELS, DUBAI, DUBLIN, FLORENCE, GRANADA, LONDON, LYON, MADRID, MILAN, PARIS, ROME, SEVILLE, VALENCIA, VIENNA
}
